commands:
- description: Writes a Haiku about this project
  name: haiku
  params:
    cheap: true
    code: false
    debug: false
    direct: false
    model: gpt-3.5-turbo
    prompt: write a haiku about this project
    repo: PR-Pilot-AI/pr-pilot-cli
    snap: false
    spinner: true
    sync: false
    verbose: true
    wait: true
- description: Run the tests, analyze the output and provide suggestions
  name: test-analysis
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/analyze_test_results.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: false
    wait: true
- description: Assemble a comprehensive daily report and send it to Slack
  name: daily-report
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/slack-report.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: false
    verbose: true
    wait: true
- description: Generate title and description for a pull request
  name: pr-description
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/generate_pr_description.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: true
    wait: true
- description: Ask a question about our K8s resources
  name: k8s-question
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/k8s-question.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: false
    verbose: false
    wait: true
