commands:
- description: Writes a Haiku about this project
  name: haiku
  params:
    cheap: true
    code: false
    debug: false
    direct: false
    model: gpt-3.5-turbo
    prompt: write a haiku about this project
    quiet: false
    repo: PR-Pilot-AI/pr-pilot-cli
    snap: false
    spinner: true
    sync: false
    wait: false
- description: Generate PR Title and Description
  name: pr-description
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/generate_pr_description.md.jinja2
    model: gpt-4o
    quiet: true
    snap: false
    spinner: false
    sync: true
    wait: true
- description: Assemble a comprehensive daily report and send it to Slack
  name: daily-report
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/slack-report.md.jinja2
    model: gpt-4o
    quiet: true
    snap: false
    spinner: true
    sync: true
    wait: true
- description: Run the tests, analyze the output and provide suggestions
  name: test-analysis
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/analyze_test_results.md.jinja2
    model: gpt-4o
    quiet: true
    snap: false
    spinner: true
    sync: true
    wait: true
