default_language_version:
  python: python3.10
repos:
  -   repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
        -   id: black
            args: ["--config=pyproject.toml"]
            language_version: python3
  -   repo: https://github.com/pycqa/flake8
      rev: '7.1.0'
      hooks:
        -   id: flake8
            language_version: python3